#!/bin/sh

# example init script for mailgraph
#
# chkconfig: 2345 82 28
# description: mailgraph postfix log grapher.
#
# processname: mailgraph.pl  qmonitor.pl
# pidfile: /var/run/mailgraph.pid  /var/run/qmonitor.pid
#
# mailgraph - by hzqbbc <hzqbbc@hzqbbc.com>

PATH=/bin:/usr/bin
BASEDIR=/var/www/extsuite/extman/daemon/mailgraph
MAILGRAPH_PL=$BASEDIR/mailgraph.pl
QMONITOR_PL=$BASEDIR/qmonitor.pl
MAIL_LOG=/var/log/maillog
MAILGRAPH_PID=/var/run/mailgraph.pid
MAILGRAPH_LOG=/var/log/mailgraph.log
QMONITOR_PID=/var/run/qmonitor.pid
QMONITOR_LOG=/var/log/qmonitor.log
RRD_DIR=/var/lib

case "$1" in
'start')
	# startup for mailgraph
	echo "Starting mail statistics grapher: mailgraph";
	nice -19 $MAILGRAPH_PL -v -d -l $MAIL_LOG \
		--daemon-pid=$MAILGRAPH_PID --daemon-log=$MAILGRAPH_LOG --daemon-rrd=$RRD_DIR

	# startup for qmonitor
	echo "Starting queue statistics grapher: qmonitor";
	nice -19 $QMONITOR_PL -v -d \
		--daemon-pid=$QMONITOR_PID --daemon-log=$QMONITOR_LOG --daemon-rrd=$RRD_DIR
	;;

'stop')
	echo "Stopping mail statistics grapher: mailgraph";
	if [ -f $MAILGRAPH_PID ]; then
		kill `cat $MAILGRAPH_PID`
		rm $MAILGRAPH_PID
	else
		echo "mailgraph not running";
	fi

	echo "Stopping queue statistics grapher: qmonitor";
	if [ -f $QMONITOR_PID ]; then
		kill `cat $QMONITOR_PID`
		rm $QMONITOR_PID
	else
		echo "qmonitor not running";
	fi
	;;

'restart')
	$0 stop
	$0 start
	;;

*)
	echo "Usage: $0 { start | restart | stop }"
	exit 1
	;;

esac
exit 0
